### ISSUE TITLE
UnsatisfiableError building on Windows

### ISSUE THREAD

**Issue by tivtom** [invenia/Keras.jl#2] opened 2017-06-23 13:42 UTC
I am running Windows 10 Pro 64-bit and get the same error, even when I use the default Conda.jl python version.

```julia
julia> ENV["PYTHON"] = ""
""

julia> Pkg.build("Keras")
INFO: Building Conda
INFO: Building PyCall
INFO: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\tiver\.julia\v0.5\Conda\deps\usr:
#
numpy                     1.13.0                   py27_0
INFO: PyCall is using C:\Users\tiver\.julia\v0.5\Conda\deps\usr\python.exe (Python 2.7.13) at C:\Users\tiver\.julia\v0.5\Conda\deps\usr\python.exe, libpython = C:\Users\tiver\.julia\v0.5\Conda\deps\usr\python27
INFO: C:\Users\tiver\.julia\v0.5\PyCall\deps\deps.jl has not changed
INFO: C:\Users\tiver\.julia\v0.5\PyCall\deps\PYTHON has not changed
INFO: Building Keras
Warning: 'conda-forge' already in 'channels' list, moving to the top
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 2.7*
  - tensorflow ==1.0.0 -> python 3.5*
Use "conda info <package>" to see the dependencies for each package.

====================================================[ ERROR: Keras ]====================================================

LoadError: failed process: Process(setenv(`'C:\Users\tiver\.julia\v0.5\Conda\deps\usr\Scripts\conda.exe' install -y tensorflow==1.0.0`,String["USERDOMAIN_ROAMINGPROFILE=THOMAS-WS","HOMEPATH=\\Users\\tiver","ProgramData=C:\\ProgramData","ProgramW6432=C:\\Program Files","PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC","SESSIONNAME=Console","APPDATA=C:\\Users\\tiver\\AppData\\Roaming","PUBLIC=C:\\Users\\Public","USERDOMAIN=THOMAS-WS","OS=Windows_NT","PROCESSOR_REVISION=2a07","TMP=C:\\Users\\tiver\\AppData\\Local\\Temp","ALLUSERSPROFILE=C:\\ProgramData","Path=C:\\Users\\tiver\\AppData\\Local\\Julia-0.5.0\\bin;C:\\Users\\tiver\\AppData\\Local\\Julia-0.5.0\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\OpenVPN\\bin;C:\\Users\\tiver\\AppData\\Local\\Julia-0.5.0\\bin;C:\\Hugo\\bin;C:\\Program Files\\Calibre2\\;C:\\Users\\tiver\\AppData\\Local\\Microsoft;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs\\;C:\\Users\\tiver\\.julia\\v0.5\\Conda\\deps\\usr\\Scripts;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Users\\tiver\\AppData\\Local\\atom\\bin;C:\\Users\\tiver\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\tiver\\AppData\\Roaming\\npm","COMPUTERNAME=THOMAS-WS","USERNAME=tiver","CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files","CommonProgramFiles=C:\\Program Files\\Common Files","CONDARC=C:\\Users\\tiver\\.julia\\v0.5\\Conda\\deps\\usr\\condarc-julia.yml","USERPROFILE=C:\\Users\\tiver","PSModulePath=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules","PROCESSOR_LEVEL=6","=C:=C:\\Users\\tiver\\.julia\\v0.5\\Keras\\deps","TEMP=C:\\Users\\tiver\\AppData\\Local\\Temp","SystemDrive=C:","HOMEDRIVE=C:","LOCALAPPDATA=C:\\Users\\tiver\\AppData\\Local","PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel","NUMBER_OF_PROCESSORS=8","ComSpec=C:\\WINDOWS\\system32\\cmd.exe","PROMPT=\$P\$G","VS140COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\","SystemRoot=C:\\WINDOWS","OneDrive=C:\\Users\\tiver\\OneDrive","CONDA_DEFAULT_ENV=C:\\Users\\tiver\\.julia\\v0.5\\Conda\\deps\\usr","ProgramFiles(x86)=C:\\Program Files (x86)","LOGONSERVER=\\\\THOMAS-WS","CONDA_PREFIX=C:\\Users\\tiver\\.julia\\v0.5\\Conda\\deps\\usr","windir=C:\\WINDOWS","FPS_BROWSER_USER_PROFILE_STRING=Default","CommonProgramW6432=C:\\Program Files\\Common Files","ProgramFiles=C:\\Program Files","FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer","PROCESSOR_ARCHITECTURE=AMD64","OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]
while loading C:\Users\tiver\.julia\v0.5\Keras\deps\build.jl, in expression starting on line 4

========================================================================================================================

====================================================[ BUILD ERRORS ]====================================================

WARNING: Keras had build errors.

 - packages with build errors remain installed in C:\Users\tiver\.julia\v0.5
 - build the package(s) and all dependencies with `Pkg.build("Keras")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================
```

I'm also happy to help/contribute if I can!

**Comment by rofinn** [comment] 2017-06-23 17:03
Thanks, I can confirm that this issue is reproducible on appveyor as well. I'll post back when I can get those builds working.

https://ci.appveyor.com/project/rofinn/keras-jl/build/job/ao60e0nc2woovjv3

**Comment by rofinn** [comment] 2017-06-23 18:14
Alright, that took a while, but the issue is that tensorflow is only supporting python 3.5 on windows. Since that is a fairly strict requirement I'm inclined to:

1. Try and use any existing keras/tensorflow install (>=2.0.0) or 
2. Install keras with the included theano backend and throw a warning.

**Comment by rofinn** [comment] 2017-07-06 16:11
Closing this issue as I've merged the windows branch into master and the tests are passing on appveyor (using the theano backend). Feel free to file a new issue if you find other problems and of course PRs are always welcome!

**Closed as completed by rofinn** 2017-07-06 16:11 UTC
